name = "Cobblemon DVidium"
author = "DV8FromTheCode"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1757deb47b41ae4d3a87d92d79c0569a6a781d53e23c292c1ecce54cc806d565"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
