name = "Cobblemon DVidium"
author = "DV8FromTheCode"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a626f82573725a5c50fcfc639022188da30e57694fe67000ad5b3cb35985840"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"
